# Site settings
title: 2 Cents
header-img: img/home-bg.jpg
email: dpeskov@yahoo.com
description: "This is easier than email"
baseurl:
url: "http://denispeskov.github.io"
twitter_username: 
github_username: 
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
