# Site settings
title: Denis Peskov
header-img: img/sun.jpg
email: dpeskov@yahoo.com
description: "Academic webpage"
baseurl:
url: "http://denispeskov.github.io"
twitter_username: 
github_username: 
facebook_username: 

# Build settings
markdown: kramdown
highlighter: rogue
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
